# -*- coding: utf-8 -*-
"""DL_Exp_10.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1e7WknlKhAWMaovXzASsmhv34Os0-JaX7
"""

!pip install onnx onnxruntime

import torch
import torchvision.models as models
import onnx
import onnxruntime as ort
import numpy as np

!pip install onnxscript

# --- Phase 1: Loading PyTorch Model ---
model = models.resnet18(weights=models.ResNet18_Weights.DEFAULT)
model.eval()

# --- Phase 2: Exporting to ONNX ---
dummy_input = torch.randn(1, 3, 224, 224)
onnx_file_path = "resnet18_deployed.onnx"

torch.onnx.export(
    model, dummy_input, onnx_file_path,
    export_params=True, opset_version=18, do_constant_folding=True,
    input_names=['input'], output_names=['output'],
    dynamic_axes={'input': {0: 'batch_size'}, 'output': {0: 'batch_size'}}
)
print("Model Exported!")

# --- Phase 3: Verifying & Testing ---
onnx_model = onnx.load(onnx_file_path)
onnx.checker.check_model(onnx_model)

ort_session = ort.InferenceSession(onnx_file_path, providers=['CPUExecutionProvider'])

def to_numpy(tensor):
    return tensor.detach().cpu().numpy() if tensor.requires_grad else tensor.cpu().numpy()

ort_inputs = {ort_session.get_inputs()[0].name: to_numpy(dummy_input)}
ort_outs = ort_session.run(None, ort_inputs)

print("Inference Successful! Output shape:", ort_outs[0].shape)

